# Site settings
title: YogiBelly
email: sahir@yogibelly.com
description: "Homemade Indian Vegetarian Food Inspired by Ayurvedic Principles"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
#  primary: ffffff
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Sunita and Mohan
  pic: 1
  position: Head Chefs
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/mohan.bhatnagar.127?fref=ts
#    - title: stack-overflow
#      url: #

- name: Sameer and Marie-Pierre
  pic: 2
  position: Management, Sales and Logistics
  social:
    - title: github
      url: https://github.com/sameerbhatnagar
    - title: home
      url: http://sameerbhatnagar.github.io/
#    - title: linkedin
#      url: #

- name: Chandni
  pic: 3
  position: Food photographer, Finance, Marketing and Social Media
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/chandnibhatnagar
    - title: facebook
      url: https://www.facebook.com/chandni.bhatnagar?fref=ts
#    - title: google-plus
#      url: #

- name: Sahir
  pic: 4
  position: Web Designer
  social:
    - title: github
      url: https://github.com/sahirbhatnagar
    - title: home
      url: http://sahirbhatnagar.com/
#    - title: google-plus
#      url: #


#- name: The Family
#  pic: 5
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/yogi_belly
#  - title: facebook
#    url: http://facebook.com/yogibelly
#  - title: instagram
#    url: http://instagram.com/yogi_belly    
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: (514) 867-3473
  - line: Montr&eacute;al, Qu&eacute;bec

# Build settings
markdown: kramdown
permalink: pretty

# Footer settings
footer:
  copyright: Yogi Belly
  location: Phone
  #social: Around the Web
  credits: Email

  # Credits content
credits:
  - line: <a href="mailto:mariepierre@yogibelly.com">mariepierre@yogibelly.com</a>
  #- line: sahiryogibelly.com 
